### PR TITLE
Fixed "*" usage in Z80 macros by copying number parameters into varia…

### PR DESCRIPTION
**Pull request by Ralakimus**
…bles before storing instruction data

### CODE REVIEW

**Comment by NatsumiFox** [comment]
This _will_ cause issues, in particular because sometimes the symbols or expressions passed as arguments rely on forward references, and trying to put expressions that can't be determined yet in variables will stop assembly. Making expressions safe in macros should be as easy as wrapping the arguments (like \1) in parenthesis instead

**Comment by cvghivebrain** [comment]
I think forward references are okay if you use equ, though I'm not sure about local variables. To be safe I went through and replaced \1 with (\1) where necessary. "dc.b \1" should be fine without brackets.

**Comment by Ralakimus** [comment]
> This _will_ cause issues, in particular because sometimes the symbols or expressions passed as arguments rely on forward references, and trying to put expressions that can't be determined yet in variables will stop assembly. Making expressions safe in macros should be as easy as wrapping the arguments (like \1) in parenthesis instead

That is why I used EQU instead of =. Because EQU is used to hold a finalized value, ASM68K sets it to be processed after assembly.

**Comment by NatsumiFox** [comment]
yeah, after talking to Rala about this, I indeed had missed the point with the changes and how they work. Indeed, equ can use forward references in many cases, and in particular here it should still work. Set (or =) in contrast can't, which is what I mainly use in macros because of global scope, but that is why local symbols were generated instead. So yeah, my bad, I made a little mistake here =P

**Pull request merged**
